
package ru.otus.webservice.soap.client;

import ru.otus.webservice.soap.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://soap.webservice.otus.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://soap.webservice.otus.ru/", className = "ru.otus.webservice.soap.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://soap.webservice.otus.ru/", className = "ru.otus.webservice.soap.AddResponse")
    @Action(input = "http://soap.webservice.otus.ru/Calculator/addRequest", output = "http://soap.webservice.otus.ru/Calculator/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
